apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-entity
  description: A test entity, see if it will be ingested automatically
  labels:
    example.com/custom: custom_label_value
  annotations:
    circleci.com/project-slug: github/pfrybar-org/test-entity
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: admin
  system: public-websites
